# PNPM Workspace Configuration for Online Trading Platform
# This file defines the workspace structure for the monorepo

packages:
  # Frontend applications
  - 'app/ui'          # Next.js frontend application
  - 'app/bff'         # NestJS Backend-for-Frontend

  # Infrastructure and tooling
  - 'infra'           # Docker, monitoring configs
  - 'tools/*'         # Development tools and scripts

# Shared dependencies configuration
# These packages will be hoisted to the root node_modules
shared-workspace-lockfile: true

# Catalog configuration for shared dependencies
catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.1

  # Next.js and related
  next: ^14.2.15
  '@next/eslint-config-next': ^14.2.15

  # NestJS ecosystem
  '@nestjs/core': ^10.4.4
  '@nestjs/common': ^10.4.4
  '@nestjs/platform-express': ^10.4.4
  '@nestjs/platform-fastify': ^10.4.4
  '@nestjs/config': ^3.2.3
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.3
  '@nestjs/swagger': ^7.4.2
  '@nestjs/websockets': ^10.4.4
  '@nestjs/platform-socket.io': ^10.4.4
  '@nestjs/typeorm': ^10.0.2
  '@nestjs/microservices': ^10.4.4
  '@nestjs/bull': ^10.2.1

  # TypeScript
  typescript: ^5.6.3
  '@types/node': ^22.7.5

  # Database and ORM
  typeorm: ^0.3.20
  pg: ^8.13.0
  '@types/pg': ^8.11.10
  redis: ^4.7.0
  '@types/redis': ^4.0.10

  # WebSocket
  socket.io: ^4.8.0
  '@types/socket.io': ^3.0.2
  ws: ^8.18.0
  '@types/ws': ^8.5.12

  # HTTP client
  axios: ^1.7.7
  '@types/axios': ^0.14.0

  # Validation
  class-validator: ^0.14.1
  class-transformer: ^0.5.1
  joi: ^17.13.3

  # Authentication
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  '@types/passport-jwt': ^4.0.1
  '@types/passport-local': ^1.0.38
  bcrypt: ^5.1.1
  '@types/bcrypt': ^5.0.2

  # Utilities
  lodash: ^4.17.21
  '@types/lodash': ^4.17.10
  moment: ^2.30.1
  uuid: ^10.0.0
  '@types/uuid': ^10.0.0

  # Development tools
  eslint: ^8.57.1
  '@typescript-eslint/eslint-plugin': ^7.18.0
  '@typescript-eslint/parser': ^7.18.0
  prettier: ^3.3.3
  husky: ^9.1.6
  lint-staged: ^15.2.10

  # Testing
  jest: ^29.7.0
  '@types/jest': ^29.5.13
  '@nestjs/testing': ^10.4.4
  supertest: ^7.0.0
  '@types/supertest': ^6.0.2

  # UI Libraries
  '@mui/material': ^6.1.3
  '@emotion/react': ^11.13.3
  '@emotion/styled': ^11.13.0
  '@mui/icons-material': ^6.1.3

  # State Management
  zustand: ^4.5.5
  '@tanstack/react-query': ^5.59.16

  # Charting
  lightweight-charts: ^4.2.1
  recharts: ^2.12.7

  # Forms
  react-hook-form: ^7.53.0
  '@hookform/resolvers': ^3.9.0
  yup: ^1.4.0

  # Styling
  tailwindcss: ^3.4.13
  '@tailwindcss/forms': ^0.5.9
  '@tailwindcss/typography': ^0.5.15

  # Date handling
  date-fns: ^4.1.0

# Peer dependency settings
save-peer: true

# Package resolution settings
auto-install-peers: true
strict-peer-dependencies: false

# Performance optimizations
shamefully-hoist: false
prefer-workspace-packages: true

# Node.js version requirement
engines:
  node: '>=18.0.0'
  pnpm: '>=8.0.0'

# Package manager settings
package-manager: 'pnpm@9.12.1'

# Publishing configuration
publishConfig:
  registry: 'https://registry.npmjs.org/'

# Workspace-level scripts that can be run from root
scripts:
  # Development
  dev: 'pnpm --parallel --stream run dev'
  dev:ui: 'pnpm --filter=ui run dev'
  dev:bff: 'pnpm --filter=bff run dev'

  # Building
  build: 'pnpm --parallel run build'
  build:ui: 'pnpm --filter=ui run build'
  build:bff: 'pnpm --filter=bff run build'

  # Testing
  test: 'pnpm --parallel run test'
  test:ui: 'pnpm --filter=ui run test'
  test:bff: 'pnpm --filter=bff run test'
  test:watch: 'pnpm --parallel run test:watch'
  test:coverage: 'pnpm --parallel run test:coverage'

  # Linting and formatting
  lint: 'pnpm --parallel run lint'
  lint:fix: 'pnpm --parallel run lint:fix'
  format: 'pnpm --parallel run format'
  format:check: 'pnpm --parallel run format:check'

  # Type checking
  typecheck: 'pnpm --parallel run typecheck'

  # Cleaning
  clean: 'pnpm --parallel run clean && rm -rf node_modules'
  clean:modules: 'find . -name "node_modules" -type d -prune -exec rm -rf {} +'

  # Dependency management
  deps:update: 'pnpm update --recursive'
  deps:outdated: 'pnpm outdated --recursive'
  deps:audit: 'pnpm audit'

  # Production
  start: 'pnpm --parallel run start'
  start:ui: 'pnpm --filter=ui run start'
  start:bff: 'pnpm --filter=bff run start'

# Workspace-specific settings
workspaces:
  packages:
    - 'app/ui'
    - 'app/bff'
    - 'infra'
    - 'tools/*'

  # Shared workspace configuration
  shared-workspace-lockfile: true
  link-workspace-packages: true